name: AuroraCombat
version: '${version}'
main: club.aurorapvp.auroracombat.AuroraCombat
api-version: '1.20'
authors: [ Villagers654 ]
description: A combat plugin for the Aurora Network
website: aurorapvp.club

permissions:
  auroracombat.command.auroracombat:
    default: true
    children:
      auroracombat.command.auroracombat.reload: false
  auroracombat.command.auroracombat.reload:
    default: false

  auroracombat.command.stats:
    default: false

  auroracombat.default:
    description: Enables basic AuroraCombat commands
    default: true
    children:
      auroracombat.command.stats: true

  auroracombat.bypass.commands:
    description: Allows for the use of commands during combat
    default: op

  auroracombat.admin:
    description: Enables use of AuroraCombat admin commands
    default: op
    children:
      auroracombat.command.auroracombat.reload: true

dependencies:
  server:
    PlaceholderAPI:
      required: false
    WorldGuard:
      required: false