name: AuroraCombat
version: '${version}'
main: club.aurorapvp.AuroraCombat
api-version: 1.19
softdepend: [ AuroraKits, AuroraDuels, PlaceholderAPI ]
authors: [ Villagers654 ]
description: A combat plugin for the Aurora Network
website: aurorapvp.club
